import { Compass, UsersRound, ShieldCheck, BadgeCheck, CalendarCheck, Sprout, ArrowRight, MapPin, HeartHandshake, MessageCircle } from 'lucide-react';
import { Link } from 'react-router-dom';
import { tours, destinations, reviews, photo } from '../../data/demo';
import TourCard from '../tour/TourCard';
import DestinationCard from '../destination/DestinationCard';
import ReviewCard from '../review/ReviewCard';
import { ButtonLink, SectionHeading } from '../common/UI';
export function PopularTours() { return <section className="container section"><SectionHeading eyebrow="Find your next adventure" title="Popular Tours" to="/tours" link="View All Tours"/><div className="tour-grid">{tours.map(t => <TourCard key={t.id} tour={t}/>)}</div><p className="sample-note">A little inspiration for your trip · Sample tours, prices and ratings</p></section>; }
export function DestinationSection() { return <section className="container section" id="destinations"><SectionHeading title="Explore by Destination" to="/destinations" link="View All Destinations"/><div className="destination-grid">{destinations.map(d => <DestinationCard key={d.slug} destination={d}/>)}</div></section>; }
const values = [[Compass, 'Local Experts', 'See the island through local eyes'], [UsersRound, 'Small Groups', 'More personal, more memorable'], [ShieldCheck, 'Safe & Reliable', 'Thoughtful planning, every step'], [BadgeCheck, 'Clear Pricing', 'Know what your adventure includes'], [CalendarCheck, 'Personal Planning', 'Find the trip that feels like you'], [Sprout, 'Meaningful Travel', 'Connect with local communities']];
export function WhyChooseUs() { return <section className="container section"><SectionHeading eyebrow="The way we want to travel" title="Why Travel With Us?"/><div className="values-grid">{values.map(([Icon, title, text]) => <article className="value-card" key={title}><span className="value-icon"><Icon size={23} strokeWidth={1.5}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>; }
export function GuideSection() { return <section className="guide-section"><div className="container guide-grid"><div className="guide-image"><img src={photo('village')} alt="Illustrative Indonesian landscape; guide portrait to be supplied" loading="lazy"/><span>Meet local people.<br/>See the real Lombok.</span></div><div className="guide-story"><span className="eyebrow">Behind every great adventure</span><h2>Your island.<br/>Your local connection.</h2><p>The best journeys are about the people you meet along the way. Our vision is simple: share the landscapes, stories and everyday moments that make Lombok special.</p><p className="sample-note">Meet your guide here soon. Their name, story and portrait are coming.</p><ButtonLink to="/about">Our Story</ButtonLink></div><div className="guide-values">{[[MapPin, 'A local perspective', 'Discover more than the landmarks'], [Compass, 'Room for discovery', 'Make time for the unexpected'], [MessageCircle, 'A personal connection', 'Start with a conversation'], [HeartHandshake, 'Support local', 'Travel with a positive impact']].map(([Icon, title, text]) => <div key={title}><span><Icon size={21}/></span><p><strong>{title}</strong><small>{text}</small></p></div>)}</div></div></section>; }
export function ReviewSection() { return <section className="container section"><SectionHeading eyebrow="A glimpse of the experience" title="Traveller Reviews" to="/reviews" link="View All Reviews"/><div className="review-grid">{reviews.filter(r => r.approved).map(r => <ReviewCard key={r.id} review={r}/>)}</div><p className="sample-note">Illustrative reviews for this preview. These are not real customer testimonials.</p></section>; }
export function AdventureCTA() { return <section className="adventure-cta" style={{ backgroundImage: `linear-gradient(90deg, #072f3dde, #064f5480), url(${photo('island')})` }}><div className="container"><span className="eyebrow">Your next story starts here</span><h2>Ready for Your Lombok Adventure?</h2><p>A little adventure. A deeper connection. A trip to remember.</p><div><ButtonLink to="/tours">Find Your Tour</ButtonLink><Link className="button light-outline" to="/contact"><MessageCircle size={18}/>Let’s Talk<ArrowRight size={16}/></Link></div></div></section>; }
