import { useParams } from 'react-router-dom';
import { getDestination, getDestinations, getTours } from '../services/catalog';
import { useData } from '../hooks/useData';
import DestinationCard from '../components/destination/DestinationCard';
import TourCard from '../components/tour/TourCard';
import { DataState, NotFound, ButtonLink } from '../components/common/UI';
import { photo } from '../data/demo';
export default function Destinations() { const state = useData(getDestinations); return <div className="container page"><div className="page-heading"><span className="eyebrow">One island, endless possibilities</span><h1>Find your kind of paradise</h1><p>From mountain trails to ocean blues. Where will Lombok take you?</p></div><DataState {...state}><div className="destination-grid listing">{state.data?.map(d => <DestinationCard key={d.slug} destination={d}/>)}</div></DataState><p className="sample-note">Some photographs are illustrative placeholders and do not depict the named destination.</p></div>; }
export function DestinationDetails() { const { slug } = useParams(); const state = useData(async () => ({ destination: await getDestination(slug), tours: await getTours({ destination: slug }) }), slug); return <DataState {...state}>{state.data && (state.data.destination ? <><section className="detail-hero" style={{ backgroundImage: `linear-gradient(0deg, #102b3acc, transparent), url(${photo(state.data.destination.image)})` }}><div className="container"><span className="eyebrow">{state.data.destination.category}</span><h1>{state.data.destination.name}</h1></div></section><div className="container page"><p className="intro-copy">{state.data.destination.description}</p><h2>Explore {state.data.destination.name}</h2>{state.data.tours.length ? <div className="tour-grid">{state.data.tours.map(t => <TourCard key={t.id} tour={t}/>)}</div> : <div className="empty-panel"><h3>More adventures are on the way</h3><p>There are no sample tours for this destination yet.</p><ButtonLink to="/tours">Explore all tours</ButtonLink></div>}<p className="sample-note">Demo destination · Imagery may be illustrative.</p></div></> : <NotFound/>)}</DataState>; }
