import { useParams, useSearchParams } from 'react-router-dom';
import { MessageCircle, MapPin } from 'lucide-react';
import { GuideSection, WhyChooseUs } from '../components/home/Sections';
import { ButtonLink, DataState, NotFound } from '../components/common/UI';
import ReviewCard from '../components/review/ReviewCard';
import { getReviews } from '../services/catalog';
import { useData } from '../hooks/useData';
import { tours } from '../data/demo';
export function About() { return <><div className="container page-heading page"><span className="eyebrow">Local people. Real experiences.</span><h1>More than a place.<br/>A connection.</h1><p>A locally focused travel concept, built around discovering Lombok with care and curiosity.</p></div><GuideSection/><WhyChooseUs/></>; }
export function Reviews() { const state = useData(getReviews); return <div className="container page"><div className="page-heading"><span className="eyebrow">Stories from the road</span><h1>Traveller Reviews</h1><p>These sample reviews show how traveller stories will look. They are not genuine testimonials.</p></div><DataState {...state}><div className="review-grid">{state.data?.map(r => <ReviewCard review={r} key={r.id}/>)}</div></DataState></div>; }
export function Contact() { const [params] = useSearchParams(); const tour = tours.find(t => t.slug === params.get('tour')); return <div className="container page contact-page"><div className="page-heading"><span className="eyebrow">Let’s plan something memorable</span><h1>Your adventure starts<br/>with a conversation.</h1><p>{tour ? `Interested in ${tour.name}? You’re in the right place.` : 'An island escape, a mountain adventure or a day of discovery.'}</p></div><div className="contact-panel"><MessageCircle size={32}/><h2>We’re getting ready to say hello</h2><p>The business’s verified WhatsApp number, email and guide details haven’t been supplied yet. Contact and booking will be available once those details are added.</p><p className="inline-icon"><MapPin size={18}/>Lombok, Indonesia</p><ButtonLink to="/tours">Keep Exploring</ButtonLink></div></div>; }
export function Information() { const { topic } = useParams(); const titles = { privacy: 'Privacy Policy', terms: 'Terms & Conditions', cancellation: 'Cancellation Policy', 'responsible-travel': 'Responsible Travel', 'photo-credits': 'Photo Credits' }; if (!titles[topic]) return <NotFound/>; return <div className="container page prose"><span className="eyebrow">Lombok Explorer</span><h1>{titles[topic]}</h1>{topic === 'photo-credits' ? <><p>Mount Rinjani photograph by Paxson Woelber, via <a href="https://commons.wikimedia.org/wiki/File:Lake_Segara_Anak,_Gunung_Baru_volcanic_crater,_and_the_summit_of_Mount_Rinjani.jpg">Wikimedia Commons</a>, licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>. The downloaded thumbnail is displayed with CSS cropping.</p><p>Other landscape placeholders are from Unsplash. They are illustrative and may not depict the named destination. See the repository’s image credits for original sources.</p></> : topic === 'responsible-travel' ? <p>Our travel vision is to respect local communities, reduce waste and leave natural places as we find them. Operator-specific practices will be added after confirmation.</p> : <p>This policy has not been supplied by the business yet. This is a frontend preview; it does not accept bookings, payments or customer submissions. Approved business policies will be published before booking launches.</p>}</div>; }
