import { useParams, Link } from 'react-router-dom';
import { Clock3, Mountain, UsersRound, Compass, Check, MapPin, ArrowLeft } from 'lucide-react';
import { getTour } from '../services/catalog';
import { useData } from '../hooks/useData';
import { destinations, money, photo } from '../data/demo';
import { ButtonLink, DataState, NotFound } from '../components/common/UI';
export default function TourDetails() {
  const { slug } = useParams(); const state = useData(() => getTour(slug), slug); const tour = state.data;
  return <DataState {...state}>{tour ? <div className="container page tour-detail"><Link to="/tours" className="text-link"><ArrowLeft size={16}/>All tours</Link><div className="page-heading"><span className="eyebrow">{destinations.find(d => d.slug === tour.destination)?.name}</span><h1>{tour.name}</h1><p className="rating">★ {tour.rating} <span>· {tour.reviewCount} sample ratings · Demo itinerary</span></p></div><img className="detail-photo" src={photo(tour.image)} alt={`${tour.name} illustrative landscape`}/><div className="detail-grid"><div><div className="quick-facts">{[[Clock3, tour.duration], [Mountain, tour.difficulty], [UsersRound, `Up to ${tour.maxGuests} guests`], [Compass, tour.activity]].map(([Icon, text]) => <span key={text}><Icon size={21}/>{text}</span>)}</div><section><h2>A little closer to the real Lombok</h2><p>{tour.description}</p></section><section><h2>The highlights</h2><ul className="check-list">{tour.highlights.map(h => <li key={h}><Check size={18}/>{h}</li>)}</ul></section><div className="inclusions"><section><h2>What’s included</h2><ul>{tour.included.map(v => <li key={v}>{v}</li>)}</ul></section><section><h2>Not included</h2><ul>{tour.excluded.map(v => <li key={v}>{v}</li>)}</ul></section></div><section><h2>Your sample itinerary</h2><div className="itinerary">{tour.itinerary.map((text, i) => <div key={text}><span>{String(i + 1).padStart(2, '0')}</span><p>{text}</p></div>)}</div></section><section><h2>What to bring</h2><ul>{tour.whatToBring.map(v => <li key={v}>{v}</li>)}</ul></section><section><h2>Meeting point</h2><p className="inline-icon"><MapPin size={20}/>{tour.meetingPoint}</p></section><section><h2>Traveller reviews</h2><p>Real traveller reviews will appear here after approval. The ratings shown in this preview are demo data.</p></section></div><aside className="booking-panel"><span className="eyebrow">Your next adventure</span><p>From <strong>{money(tour.price)}</strong><small>per person · Sample price</small></p><h3>Good things are on the way</h3><p>Online bookings are coming soon. Explore this sample tour and get inspired for your trip.</p><ButtonLink to={`/contact?tour=${tour.slug}`}>Ask About This Tour</ButtonLink><p className="sample-note">Dates, inclusions, availability and final pricing will be confirmed by the operator. No booking or payment is taken in this preview.</p></aside></div><div className="mobile-book"><span>From <strong>{money(tour.price)}</strong></span><ButtonLink to={`/contact?tour=${tour.slug}`}>Enquire</ButtonLink></div></div> : !state.loading && <NotFound/>}</DataState>;
}
